http://localhost:8080/clientes


####
http://localhost:8080/eventos

####

http://localhost:8080/casashow


####

PUT    http://localhost:8080/clientes/3 HTTP/1.1
content-type: application/json

{
    "nome": "zé",
    "email": "ze@.com.",
    "telefone": "12341234",
    "senha": "123456"
    
}
